name: Little Foxes
description: Writings on tech and foxes
meta_description: "Writings on tech and foxes"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'https://littlefox.es'
google_analytics: 'UA-XXXXXXXX-X'
permalink: none
gems: [jekyll-paginate, gemoji, html/pipeline]

timezone: Asia/Kuala_Lumpur
future: true

emoji:
  src: "/img"

# Details for the RSS feed generator
url:            'https://littlefox.es'
author:         'soulchild'
bio:            "I dream of foxes and a world where software doesn't suck"
