# Site settings
name: Little Foxes
title: Little Foxes
description: Writings about technology and appreciation of foxes
markdown: kramdown
highlighter: pygments
paginate: 10
paginate_path: "page/:num/"
permalink: none
timezone: Asia/Kuala_Lumpur
future: true

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://littlefox.es" # the base hostname & protocol for your site

emoji:
  src: "/img"


# Gems
gems: [jekyll-paginate, gemoji, html/pipeline]

# Build settings
markdown: kramdown
kramdown:
  entity_output: as_input